### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ThoastDev** [Holo5/nitro-docker#9] opened 2023-06-12 04:09 UTC
Hi guys.

I'm trying test this nitro-docker, but when i run the `just start-all` apparently all is building with success, but shows me a warning related to mysql, the warning:

`mysql     | 2023-06-12  3:56:52 3 [Warning] Aborted connection 3 to db: 'arcturus' user: 'arcturus_user' host: '172.18.0.4' (Got an error reading communication packets)`

In the browser console i can see this error: 

`SocketConnection.ts:98 WebSocket connection to 'ws://127.0.0.1:2096/' failed: `

I'm running the nitro-docker in a Macbook M1, i would know what is the problem and i you can help me.

Thanks.

**Comment by Pi-Bouf** [comment] 2023-06-12 16:18
Outch ! I will investigate right now, coming back soon 🥲🔍

**Comment by eduardhojbota** [comment] 2023-07-17 11:36
@Pi-Bouf, it might be necessary to update the `db.port` setting in the `emulator/config.ini` file to `13306`. This change aligns with the configuration in the `docker-compose.yaml` file, where the MySQL service is set up to run on the external port `13306`. 

Making this modification resolved the warning for me. 

However, even after this adjustment, I still encounter the error `SocketConnection.ts:98 WebSocket connection to 'ws://127.0.0.1:2096/' failed:` in the browser.

**Comment by Pi-Bouf** [comment] 2023-07-19 14:06
Yeah but the problem is mysql on mac M1 doesn't work :(

**Comment by rauldeheer** [comment] 2023-07-21 12:25
@Pi-Bouf False. I'm running this on a M1. There's no problem with running MySQL on ARM.

**Comment by Pi-Bouf** [comment] 2023-07-21 17:17
It was true before @rauldeheer ! 😂 That's why

**Comment by Pi-Bouf** [comment] 2023-08-01 18:11
HELLO @ThoastDev , @eduardhojbota , @rauldeheer 
This issue is fixed now, with all latest version of everything (except MS)

https://github.com/Holo5/nitro-docker/commit/4d2275133c6f2084db2778b63749522e723964fb

**Closed** 2023-08-06 22:28 UTC
Labels: FIXED
